name: Verify private branch builds successfully

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/common-build.yaml
    with:
      build-dir: private-branch-build
