name: Verify private branch builds successfully

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/common-build.yaml
    with:
      build-dir: private-branch-build
      version-str: "0.0.0"
      coverage-threshold: "95"

  all-checks-passed:
    name: All Builds and Tests Passed
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All matrix builds and coverage checks passed successfully."
