name: Build with MSVC/CMake

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [x64, ARM64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S src -B build-${{ matrix.arch }} -G "Visual Studio 17 2022" -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build-${{ matrix.arch }} --config RelWithDebInfo

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ShellExecuteEx-${{ matrix.arch }}
          path: |
            build-${{ matrix.arch }}/RelWithDebInfo/*.exe
            build-${{ matrix.arch }}/RelWithDebInfo/*.pdb
        
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Download x86-64 binaries
        uses: actions/download-artifact@v4
        with:
          name: ShellExecuteEx-x64
          path: build-x64

      - name: Download ARM64 binaries
        uses: actions/download-artifact@v4
        with:
          name: ShellExecuteEx-ARM64
          path: build-ARM64

      - name: Zip them together
        run: |
          mkdir -p release
          cp build-x64/* release/
          cp build-ARM64/* release/
          zip -r release/ShellExecuteEx-${{ github.run_number }}-windows.zip release/*

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/ShellExecuteEx-${{ github.run_number }}-windows.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
