name: Build with MSVC/CMake

on:
  push:
    branches: [ build-test ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [x64, ARM64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build-${{ matrix.arch }} -G "Visual Studio 17 2022" -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build-${{ matrix.arch }} --config Release
